# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LaserTag")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LaserTag")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
